### PR TITLE
Ecodata playground

### PR DESCRIPTION
**Pull request by kimberly-bastille**
Done -  
1) geom_gls() added to arfit.
2) built arfit::geom_lm() - just includes linear_ar1 from geom_gls()
3) Removed docs from gitignore 
4) Built docs/SOE_workshop_trends.Rmd - includes forced LM using ggplot2::geom_smooth and two examples of arfit::geom_lm() 

To Do -
1) Add your model process to StatLM
2) Uncomment if Pvalue > 0.5 in StatLM

### CODE REVIEW

**Comment by andybeet** [comment]
@kimberly-bastille just moved rmd to vignettes since i have docs protected for local use. This works like a charm. nice job

**Comment by kimberly-bastille** [comment]
Ok should the rmd eventually move back to docs after we finish the build/SOE pres? I don't think that should get included in your pkgdown site for when you publish.

**Comment by andybeet** [comment]
I agree. What i think i'd like to do is to move all of this content to another repo. I already have a repo called [`soenotes`.](https://andybeet.github.io/soenotes/). This repo is for my exploration work related to SOE products. I should have thought about this beforehand but was unsure of how this geom would all come together. Since the code you added calls `arfit::funcName` this Rmd and the associated files could reside anywhere. Does that make sense? If so do you mind if i just move all of this to that repo?

**Comment by kimberly-bastille** [comment]
I think we should finish building the geom_lm first just to keep the playground in one place. Then once your lm analysis in is in we can 1)remove the gls from arfit. 2) move geom_lm, Geom_LM, and StatLM to ecodata. 3) move the rmd to soenotes and switchout the arfit::geom_lm() to ecodata::geom_lm(). That will keep arfit clean for publication and make ecodata plotting contained.

**Comment by kimberly-bastille** [comment]
Also, Unrelated and Minor but I found a typo printing issue in the background vignette. An equation in the "Likelihood for AR(2) errors" wasn't showing up in the equation format so I fix that in this branch.

**Comment by andybeet** [comment]
Not going to merge this. Code has been transferred to `ecodata`, and other changes made to another branch

**Pull request closed without merging**
